# Generated by Django 4.0 on 2022-01-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_date', models.DateTimeField()),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit_history_email', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('address_prefecture', models.CharField(max_length=10)),
                ('address_city', models.CharField(max_length=20)),
                ('hear_from', models.CharField(max_length=30)),
                ('introduced', models.CharField(max_length=40, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_email', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('visit_count', models.IntegerField(default=0)),
                ('continuous_visit_count', models.IntegerField(default=0)),
                ('previous_visit', models.DateTimeField(null=True)),
                ('last_visit', models.DateTimeField(null=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_email', to='core.user')),
            ],
        ),
    ]
